version: 0.0
os: linux
files:
  - source: /buildspec.yml
    destination: /home/ubuntu/k8s
  - source: /applicationstart.sh
    destination: /home/ubuntu/k8s
hooks:
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100

