version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/napp
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
