version: 0.0
os: linux
files:
  - source: /buildspec.yml
    destination: /home/ubuntu/k8s
  - source: /afterinstall.sh
    destination: /home/ubuntu/k8s
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100

